/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IU;

import excecao.TamanhoInvalidoException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.JLabel;
import javax.swing.JRadioButton;
import pontuacao.Aurora;
import pontuacao.Cincos;
import pontuacao.Dois;
import pontuacao.DoisPares;
import pontuacao.FullHouse;
import pontuacao.Par;
import pontuacao.Pontuacao;
import pontuacao.Quadra;
import pontuacao.Quatros;
import pontuacao.Seis;
import pontuacao.SequenciaMaior;
import pontuacao.SequenciaMenor;
import pontuacao.Tres;
import pontuacao.Trio;
import pontuacao.Uns;
import sistema.ConjuntoDeDados;
import sistema.ConjuntoDePontuacoes;
import sistema.Dado;

/**
 *
 * @author jmarc
 */
public class JFJogo extends javax.swing.JFrame {

    /**
     * Creates new form JFJogo
     */
    public JFJogo() {
        initComponents();
        pontuacaoTotal = 0;
        uptadePontuacaoTotal();
        ArrayList<Dado> listaDados = new ArrayList<>();
        for (int i = 0; i < 5; i++){
            listaDados.add(new Dado());
        }
        try {
            dados = new ConjuntoDeDados(listaDados);
        } catch (TamanhoInvalidoException ex) {
        }
        
        ArrayList<Pontuacao> regras = new ArrayList<>();
        regras.add(new Aurora());
        regras.add(new Cincos());
        regras.add(new Dois());
        regras.add(new DoisPares());
        regras.add(new FullHouse());
        regras.add(new Par());
        regras.add(new Quadra());
        regras.add(new Quatros());
        regras.add(new Seis());
        regras.add(new SequenciaMaior());
        regras.add(new SequenciaMenor());
        regras.add(new Tres());
        regras.add(new Trio());
        regras.add(new Uns());
        try {
            pontuacoes = new ConjuntoDePontuacoes(regras);
        } catch (TamanhoInvalidoException ex) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabelDado1 = new javax.swing.JLabel();
        jLabelDado2 = new javax.swing.JLabel();
        jLabelDado3 = new javax.swing.JLabel();
        jLabelDado4 = new javax.swing.JLabel();
        jLabelDado5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jRadioUns = new javax.swing.JRadioButton();
        jRadioDois = new javax.swing.JRadioButton();
        jRadioTres = new javax.swing.JRadioButton();
        jRadioQuatros = new javax.swing.JRadioButton();
        jRadioCincos = new javax.swing.JRadioButton();
        jRadioPar = new javax.swing.JRadioButton();
        jRadioDoisPares = new javax.swing.JRadioButton();
        jRadioTrio = new javax.swing.JRadioButton();
        jRadioQuadra = new javax.swing.JRadioButton();
        jRadioSeis = new javax.swing.JRadioButton();
        jRadioSequenciaMenor = new javax.swing.JRadioButton();
        jRadioSequenciaMaior = new javax.swing.JRadioButton();
        jRadioFullHouse = new javax.swing.JRadioButton();
        jRadioAurora = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButtonEscolherCategoria = new javax.swing.JButton();
        jLabelNome = new javax.swing.JLabel();
        jLabelCondicao = new javax.swing.JLabel();
        jLabelRegra = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelPontucaoTotal = new javax.swing.JLabel();
        jButtonRolar = new javax.swing.JButton();
        jButtonVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(" Jogar Aurora");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelDado1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/dice-0.png"))); // NOI18N

        jLabelDado2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/dice-0.png"))); // NOI18N

        jLabelDado3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/dice-0.png"))); // NOI18N

        jLabelDado4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/dice-0.png"))); // NOI18N

        jLabelDado5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/dice-0.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelDado1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabelDado2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabelDado3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabelDado4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabelDado5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelDado5)
                    .addComponent(jLabelDado2)
                    .addComponent(jLabelDado1)
                    .addComponent(jLabelDado3)
                    .addComponent(jLabelDado4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Categorias", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        buttonGroup1.add(jRadioUns);
        jRadioUns.setText("Uns");
        jRadioUns.setEnabled(false);
        jRadioUns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioUnsActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioDois);
        jRadioDois.setText("Dois");
        jRadioDois.setEnabled(false);
        jRadioDois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioDoisActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioTres);
        jRadioTres.setText("Tres");
        jRadioTres.setEnabled(false);
        jRadioTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioTresActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioQuatros);
        jRadioQuatros.setText("Quatros");
        jRadioQuatros.setEnabled(false);
        jRadioQuatros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioQuatrosActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioCincos);
        jRadioCincos.setText("Cincos");
        jRadioCincos.setEnabled(false);
        jRadioCincos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioCincosActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioPar);
        jRadioPar.setText("Par");
        jRadioPar.setEnabled(false);
        jRadioPar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioParActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioDoisPares);
        jRadioDoisPares.setText("Dois Pares");
        jRadioDoisPares.setEnabled(false);
        jRadioDoisPares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioDoisParesActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioTrio);
        jRadioTrio.setText("Trio");
        jRadioTrio.setEnabled(false);
        jRadioTrio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioTrioActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioQuadra);
        jRadioQuadra.setText("Quadra");
        jRadioQuadra.setEnabled(false);
        jRadioQuadra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioQuadraActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioSeis);
        jRadioSeis.setText("Seis");
        jRadioSeis.setEnabled(false);
        jRadioSeis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioSeisActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioSequenciaMenor);
        jRadioSequenciaMenor.setText("Sequencia Menor");
        jRadioSequenciaMenor.setEnabled(false);
        jRadioSequenciaMenor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioSequenciaMenorActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioSequenciaMaior);
        jRadioSequenciaMaior.setText("Sequencia Maior");
        jRadioSequenciaMaior.setEnabled(false);
        jRadioSequenciaMaior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioSequenciaMaiorActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioFullHouse);
        jRadioFullHouse.setText("Full House");
        jRadioFullHouse.setEnabled(false);
        jRadioFullHouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioFullHouseActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioAurora);
        jRadioAurora.setText("Aurora");
        jRadioAurora.setEnabled(false);
        jRadioAurora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioAuroraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jRadioDois)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioPar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioSequenciaMaior))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jRadioTres)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioDoisPares)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioFullHouse))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jRadioQuatros)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioTrio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioAurora))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jRadioCincos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioQuadra)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jRadioUns)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioSeis)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioSequenciaMenor)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jRadioAurora, jRadioCincos, jRadioDois, jRadioDoisPares, jRadioFullHouse, jRadioPar, jRadioQuadra, jRadioQuatros, jRadioSeis, jRadioSequenciaMaior, jRadioSequenciaMenor, jRadioTres, jRadioTrio, jRadioUns});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioUns)
                    .addComponent(jRadioSeis)
                    .addComponent(jRadioSequenciaMenor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioDois)
                    .addComponent(jRadioPar)
                    .addComponent(jRadioSequenciaMaior))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioTres)
                    .addComponent(jRadioDoisPares)
                    .addComponent(jRadioFullHouse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioQuatros)
                    .addComponent(jRadioTrio)
                    .addComponent(jRadioAurora))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioCincos)
                    .addComponent(jRadioQuadra))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Descricao", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13))); // NOI18N

        jLabel2.setText("Nome:");

        jLabel3.setText("Condicao:");

        jLabel4.setText("Regra:");

        jButtonEscolherCategoria.setText("Escolher Esse");
        jButtonEscolherCategoria.setEnabled(false);
        jButtonEscolherCategoria.setFocusPainted(false);
        jButtonEscolherCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEscolherCategoriaActionPerformed(evt);
            }
        });

        jLabelNome.setText(" ");
        jLabelNome.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabelCondicao.setBackground(new java.awt.Color(255, 255, 255));
        jLabelCondicao.setText(" ");
        jLabelCondicao.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabelRegra.setText(" ");
        jLabelRegra.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelRegra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelCondicao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonEscolherCategoria)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonEscolherCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelCondicao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelRegra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Pontuacao Atual:");

        jLabelPontucaoTotal.setBackground(new java.awt.Color(255, 255, 255));
        jLabelPontucaoTotal.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabelPontucaoTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPontucaoTotal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPontucaoTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelPontucaoTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButtonRolar.setText("Iniciar");
        jButtonRolar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRolarActionPerformed(evt);
            }
        });

        jButtonVoltar.setText("Voltar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonVoltar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonRolar)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonRolar, jButtonVoltar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRolar)
                    .addComponent(jButtonVoltar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRolarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRolarActionPerformed
        jButtonEscolherCategoria.setEnabled(true);
        jRadioAurora.setEnabled(true);
        jRadioCincos.setEnabled(true);
        jRadioDois.setEnabled(true);
        jRadioDoisPares.setEnabled(true);
        jRadioFullHouse.setEnabled(true);
        jRadioPar.setEnabled(true);
        jRadioQuadra.setEnabled(true);
        jRadioQuatros.setEnabled(true);
        jRadioSeis.setEnabled(true);
        jRadioSequenciaMaior.setEnabled(true);
        jRadioSequenciaMenor.setEnabled(true);
        jRadioTres.setEnabled(true);
        jRadioTrio.setEnabled(true);
        jRadioUns.setEnabled(true);
        jButtonRolar.setEnabled(false);
        JLabel[] labels = {jLabelDado1,jLabelDado2,jLabelDado3,jLabelDado4,jLabelDado5};
        int[] valores = dados.rolarTodos();
        for (int i = 0; i < 5; i++){
            Icon icon;
            switch (valores[i]){
                case 1:
                    icon = new javax.swing.ImageIcon(getClass().getResource("/recursos/dice-1.png"));
                    break;
                case 2:
                    icon = new javax.swing.ImageIcon(getClass().getResource("/recursos/dice-2.png"));
                    break;
                case 3:
                    icon = new javax.swing.ImageIcon(getClass().getResource("/recursos/dice-3.png"));
                    break;
                case 4:
                    icon = new javax.swing.ImageIcon(getClass().getResource("/recursos/dice-4.png"));
                    break;
                case 5:
                    icon = new javax.swing.ImageIcon(getClass().getResource("/recursos/dice-5.png"));
                    break;
                case 6:
                    icon = new javax.swing.ImageIcon(getClass().getResource("/recursos/dice-6.png"));
                    break;
                default:
                    icon = new javax.swing.ImageIcon(getClass().getResource("/recursos/dice-0.png"));
            }
            
            labels[i].setIcon(icon);
        }
    }//GEN-LAST:event_jButtonRolarActionPerformed

    private void jRadioUnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioUnsActionPerformed
        uptadeDetalhesDasRegras(pontuacoes.encontrarRegraPorNome("Uns"));
    }//GEN-LAST:event_jRadioUnsActionPerformed

    private void jRadioDoisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioDoisActionPerformed
        uptadeDetalhesDasRegras(pontuacoes.encontrarRegraPorNome("Dois"));
    }//GEN-LAST:event_jRadioDoisActionPerformed

    private void jRadioTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioTresActionPerformed
        uptadeDetalhesDasRegras(pontuacoes.encontrarRegraPorNome("Tres"));
    }//GEN-LAST:event_jRadioTresActionPerformed

    private void jRadioQuatrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioQuatrosActionPerformed
        uptadeDetalhesDasRegras(pontuacoes.encontrarRegraPorNome("Quatros"));
    }//GEN-LAST:event_jRadioQuatrosActionPerformed

    private void jRadioCincosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioCincosActionPerformed
        uptadeDetalhesDasRegras(pontuacoes.encontrarRegraPorNome("Cincos"));
    }//GEN-LAST:event_jRadioCincosActionPerformed

    private void jRadioSeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioSeisActionPerformed
        uptadeDetalhesDasRegras(pontuacoes.encontrarRegraPorNome("Seis"));
    }//GEN-LAST:event_jRadioSeisActionPerformed

    private void jRadioParActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioParActionPerformed
        uptadeDetalhesDasRegras(pontuacoes.encontrarRegraPorNome("Par"));
    }//GEN-LAST:event_jRadioParActionPerformed

    private void jRadioDoisParesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioDoisParesActionPerformed
        uptadeDetalhesDasRegras(pontuacoes.encontrarRegraPorNome("Dois Pares"));
    }//GEN-LAST:event_jRadioDoisParesActionPerformed

    private void jRadioTrioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioTrioActionPerformed
        uptadeDetalhesDasRegras(pontuacoes.encontrarRegraPorNome("Trio"));
    }//GEN-LAST:event_jRadioTrioActionPerformed

    private void jRadioQuadraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioQuadraActionPerformed
        uptadeDetalhesDasRegras(pontuacoes.encontrarRegraPorNome("Quadra"));
    }//GEN-LAST:event_jRadioQuadraActionPerformed

    private void jRadioSequenciaMenorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioSequenciaMenorActionPerformed
        uptadeDetalhesDasRegras(pontuacoes.encontrarRegraPorNome("Sequencia Menor"));
    }//GEN-LAST:event_jRadioSequenciaMenorActionPerformed

    private void jRadioSequenciaMaiorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioSequenciaMaiorActionPerformed
        uptadeDetalhesDasRegras(pontuacoes.encontrarRegraPorNome("Sequencia Maior"));
    }//GEN-LAST:event_jRadioSequenciaMaiorActionPerformed

    private void jRadioFullHouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioFullHouseActionPerformed
        uptadeDetalhesDasRegras(pontuacoes.encontrarRegraPorNome("Full House"));
    }//GEN-LAST:event_jRadioFullHouseActionPerformed

    private void jRadioAuroraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioAuroraActionPerformed
        uptadeDetalhesDasRegras(pontuacoes.encontrarRegraPorNome("Aurora"));
    }//GEN-LAST:event_jRadioAuroraActionPerformed

    private void jButtonEscolherCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEscolherCategoriaActionPerformed
        Pontuacao regra = pontuacoes.encontrarRegraPorNome(jLabelNome.getText());
        pontuacaoTotal += regra.getPontuacao(dados);
        uptadePontuacaoTotal();
        jButtonRolarActionPerformed(null);
    }//GEN-LAST:event_jButtonEscolherCategoriaActionPerformed

    private void uptadeDetalhesDasRegras(Pontuacao regra){
        jLabelNome.setText(regra.getNome());
        jLabelCondicao.setText(regra.getCondicao());
        jLabelRegra.setText(regra.getRegra());
    }
    
    private void uptadePontuacaoTotal(){
        jLabelPontucaoTotal.setText(pontuacaoTotal.toString());
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFJogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonEscolherCategoria;
    private javax.swing.JButton jButtonRolar;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelCondicao;
    private javax.swing.JLabel jLabelDado1;
    private javax.swing.JLabel jLabelDado2;
    private javax.swing.JLabel jLabelDado3;
    private javax.swing.JLabel jLabelDado4;
    private javax.swing.JLabel jLabelDado5;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelPontucaoTotal;
    private javax.swing.JLabel jLabelRegra;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioAurora;
    private javax.swing.JRadioButton jRadioCincos;
    private javax.swing.JRadioButton jRadioDois;
    private javax.swing.JRadioButton jRadioDoisPares;
    private javax.swing.JRadioButton jRadioFullHouse;
    private javax.swing.JRadioButton jRadioPar;
    private javax.swing.JRadioButton jRadioQuadra;
    private javax.swing.JRadioButton jRadioQuatros;
    private javax.swing.JRadioButton jRadioSeis;
    private javax.swing.JRadioButton jRadioSequenciaMaior;
    private javax.swing.JRadioButton jRadioSequenciaMenor;
    private javax.swing.JRadioButton jRadioTres;
    private javax.swing.JRadioButton jRadioTrio;
    private javax.swing.JRadioButton jRadioUns;
    // End of variables declaration//GEN-END:variables
    
    //Declaration of personal variables
    private ConjuntoDeDados dados;
    private ConjuntoDePontuacoes pontuacoes;
    private Integer pontuacaoTotal;
}
