/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IU.Panels;

import excecao.TamanhoInvalidoException;
import java.util.ArrayList;
import pontuacao.*;
import sistema.*;

/**
 *
 * @author jmarc
 */
public class JPMelhorEscolha extends javax.swing.JPanel {

    /**
     * Creates new form JPMelhorEscolha
     */
    public JPMelhorEscolha() {
        initComponents();
        ArrayList<Dado> listaDados = new ArrayList<>();
        for (int i = 0; i < 5; i++){
            listaDados.add(new Dado());
        }
        try {
            dados = new ConjuntoDeDados(listaDados);
        } catch (TamanhoInvalidoException ex) {
        }
        
        ArrayList<Pontuacao> regras = new ArrayList<>();
        regras.add(new Uns());
       	regras.add(new Dois());
	regras.add(new Tres());
	regras.add(new Quatros());
	regras.add(new Cincos());
	regras.add(new Seis());
	regras.add(new Par());
	regras.add(new DoisPares());
	regras.add(new Trio());
	regras.add(new Quadra());
	regras.add(new SequenciaMenor());
	regras.add(new SequenciaMaior());
	regras.add(new FullHouse());
	regras.add(new Aurora());
        try {
            pontuacoes = new ConjuntoDePontuacoes(regras);
        } catch (TamanhoInvalidoException ex) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinnerDado1 = new javax.swing.JSpinner();
        jSpinnerDado2 = new javax.swing.JSpinner();
        jSpinnerDado3 = new javax.swing.JSpinner();
        jSpinnerDado4 = new javax.swing.JSpinner();
        jSpinnerDado5 = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabelNomeCategoria = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelPontuacaoCategoria = new javax.swing.JLabel();
        jButtonCalcular = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(400, 300));

        jSpinnerDado1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 6, 1));

        jSpinnerDado2.setModel(new javax.swing.SpinnerNumberModel(1, 1, 6, 1));

        jSpinnerDado3.setModel(new javax.swing.SpinnerNumberModel(1, 1, 6, 1));

        jSpinnerDado4.setModel(new javax.swing.SpinnerNumberModel(1, 1, 6, 1));

        jSpinnerDado5.setModel(new javax.swing.SpinnerNumberModel(1, 1, 6, 1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Melhor Escolha de Categoria:");

        jLabelNomeCategoria.setText(" ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Pontuacao Dessa Categoria:");

        jLabelPontuacaoCategoria.setText(" ");

        jButtonCalcular.setText("Calcular");
        jButtonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSpinnerDado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jSpinnerDado2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jSpinnerDado3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jSpinnerDado4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jSpinnerDado5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPontuacaoCategoria)
                            .addComponent(jLabelNomeCategoria))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonCalcular)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jSpinnerDado1, jSpinnerDado2, jSpinnerDado3, jSpinnerDado4, jSpinnerDado5});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerDado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerDado2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerDado3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerDado4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerDado5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelNomeCategoria)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelPontuacaoCategoria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonCalcular)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularActionPerformed
        try {
            jSpinnerDado1.commitEdit();
            jSpinnerDado2.commitEdit();
            jSpinnerDado3.commitEdit();
            jSpinnerDado4.commitEdit();
            jSpinnerDado5.commitEdit();
        } catch ( java.text.ParseException e ) {
        }
        int[] valores = {(Integer) jSpinnerDado1.getValue(),
                         (Integer) jSpinnerDado2.getValue(),
                         (Integer) jSpinnerDado3.getValue(),
                         (Integer) jSpinnerDado4.getValue(),
                         (Integer) jSpinnerDado5.getValue()
                        };
        dados.setValores(valores);
        Pontuacao melhor = pontuacoes.calcularMelhorRegra(dados);
        jLabelNomeCategoria.setText(melhor.getNome());
        Integer pontuacao = melhor.getPontuacao(dados);
        jLabelPontuacaoCategoria.setText(pontuacao.toString());
    }//GEN-LAST:event_jButtonCalcularActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCalcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelNomeCategoria;
    private javax.swing.JLabel jLabelPontuacaoCategoria;
    private javax.swing.JSpinner jSpinnerDado1;
    private javax.swing.JSpinner jSpinnerDado2;
    private javax.swing.JSpinner jSpinnerDado3;
    private javax.swing.JSpinner jSpinnerDado4;
    private javax.swing.JSpinner jSpinnerDado5;
    // End of variables declaration//GEN-END:variables
    
    //Declaration of personal variables
    private ConjuntoDeDados dados;
    private ConjuntoDePontuacoes pontuacoes;

}
